//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDS_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public int project_id { get; set; }
        public string project_name { get; set; }
        public string timeStart { get; set; }
        public string timeEnd { get; set; }
        public string locations { get; set; }
        public string descriptions { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual employee employee { get; set; }
    }
}
